
inductive Tree (α : Type u) where
  | leaf
  | node (left : Tree α) (a : α) (right : Tree α)

def Tree.map (f : α → β) : Tree α → Tree β
  | .leaf => .leaf
  | .node l a r => .node (map f l) (f a) (map f r)

/-!
The rest of this file was generated by Claude Code using the prompt
"
I have the file @tests/leo/exp.lean. It contains the recursive function `Tree.map`.
I want you to implement a tail recursive version, and prove it computes the same result of `Tree.map`.
"
-/

namespace Tree

def size : Tree α → Nat
  | .leaf => 0
  | .node l _ r => 1 + l.size + r.size

/-- Stack frame for tail-recursive tree map. -/
inductive Frame (α : Type u) (β : Type v) where
  | visit (val : β) (right : Tree α)
  | done (left : Tree β) (val : β)

def stackWeight : List (Frame α β) → Nat
  | [] => 0
  | .visit _ r :: s => 4 * r.size + 3 + stackWeight s
  | .done _ _ :: s => 1 + stackWeight s

mutual
  /-- Go phase: descend into the tree, pushing frames onto the stack. -/
  def mapGo (f : α → β) (stack : List (Frame α β)) (t : Tree α) : Tree β :=
    match t with
    | .node l a r => mapGo f (.visit (f a) r :: stack) l
    | .leaf => mapBack f stack .leaf
  termination_by 4 * t.size + stackWeight stack + 1
  decreasing_by all_goals simp only [stackWeight, size]; omega

  /-- Back phase: ascend from leaves, consuming frames from the stack. -/
  def mapBack (f : α → β) (stack : List (Frame α β)) (result : Tree β) : Tree β :=
    match stack with
    | .visit a r :: rest => mapGo f (.done result a :: rest) r
    | .done l a :: rest => mapBack f rest (.node l a result)
    | [] => result
  termination_by stackWeight stack
  decreasing_by all_goals simp only [stackWeight]; omega
end

/-- Tail-recursive tree map. -/
def mapTR (f : α → β) (t : Tree α) : Tree β :=
  mapGo f [] t

/-- Interpret the stack as a context applied to a result tree.
    Each `visit` frame means "the right subtree still needs mapping".
    Each `done` frame means "combine with the already-mapped left subtree". -/
def applyStack (f : α → β) : List (Frame α β) → Tree β → Tree β
  | [], result => result
  | .visit a r :: stack, left => applyStack f stack (.node left a (map f r))
  | .done l a :: stack, right => applyStack f stack (.node l a right)

mutual
  theorem mapGo_spec (f : α → β) (stack : List (Frame α β)) (t : Tree α) :
      mapGo f stack t = applyStack f stack (map f t) := by
    match t with
    | .node l a r =>
      unfold mapGo
      rw [mapGo_spec f (.visit (f a) r :: stack) l]
      rfl
    | .leaf =>
      unfold mapGo
      exact mapBack_spec f stack .leaf
  termination_by 4 * t.size + stackWeight stack + 1
  decreasing_by all_goals simp only [stackWeight, size]; omega

  theorem mapBack_spec (f : α → β) (stack : List (Frame α β)) (result : Tree β) :
      mapBack f stack result = applyStack f stack result := by
    match stack with
    | [] => simp only [mapBack, applyStack]
    | .done l a :: rest =>
      unfold mapBack
      rw [mapBack_spec f rest (.node l a result)]
      rfl
    | .visit a r :: rest =>
      unfold mapBack
      rw [mapGo_spec f (.done result a :: rest) r]
      rfl
  termination_by stackWeight stack
  decreasing_by all_goals simp only [stackWeight]; omega
end

/-- The tail-recursive map computes the same result as the naive map. -/
theorem mapTR_eq_map (f : α → β) (t : Tree α) : mapTR f t = map f t := by
  simp only [mapTR, mapGo_spec, applyStack]

end Tree
